### ISSUE TITLE
Pop-ups remain open in dhatupatha page when navigating to other pages

### ISSUE THREAD

**Issue by vipranarayan14** [ashtadhyayi-com/code#9]
![Screenshot 2024-06-04 at 8 23 33 PM](https://github.com/ashtadhyayi-com/code/assets/17687018/080eb7d0-8adf-4fcc-945c-3bda60a2270a)

**Comment by neeleshb** [comment]
Can you please elaborate the exact steps to reproduce the issue

**Comment by vipranarayan14** [comment]
Sorry, didn't give much info earlier. I have had this issue at least for a year or two now. So, thought the issue was obvious.  But just now found out that the issue is only in Firefox (my earlier go-to browser) and Safari (my current browser) but not in Chrome!

Screen rec from Firefox for steps to reproduce:

https://github.com/ashtadhyayi-com/code/assets/17687018/4ef7ad4b-c643-487c-98f7-c1b06fc3c5b0
